#!/bin/bash
cp newuser /usr/bin/newuser
chmod 700 /usr/bin/newuser
chown root /usr/bin/newuser
cp scripttocommand.sh /usr/bin/stc
chmod 700 /usr/bin/stc
chown root /usr/bin/stc
cp updatemykali /usr/bin/updatemykali
chmod 700 /usr/bin/updatemykali
chown root /usr/bin/updatemykali
