#!/bin/bash

echo "installing packeges by Avi Twill . . ."
sleep 3
cp newuser /usr/bin/newuser
chmod 700 /usr/bin/newuser
chown root /usr/bin/newuser
cp scripttocommand.sh /usr/bin/stc
chmod 700 /usr/bin/stc
chown root /usr/bin/stc
cp updatemykali /usr/bin/updatemykali
chmod 700 /usr/bin/updatemykali
chown root /usr/bin/updatemykali

echo " installation coplete"
echo " newuser -- create new user Just better "
echo " stc [script file] [command name] [sudo/nothing] -- take a scripte file and turn it in to a command "
echo " updatemykaly -- doing updates and upgrades automaticly , no inputs needed"
echo " Enjoy"

