#!/bin/bash
cp newuser /usr/bin/newuser
chmod 700 /usr/bin/newuser
chown root /usr/bin/newuser
cp scripttocommand.sh /usr/bin/stc
chmod 700 /usr/bin/stc
chown root /usr/bin/stc
cp updatemykaly /usr/bin/updatemykaly
chmod 700 /usr/bin/updatemykaly
chown root /usr/bin/updatemykaly
